language: cpp

os: linux
dist: bionic
arch:
  - amd64
  - arm64
  - ppc64le

addons:
  apt:
    packages:
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev

script:
  - mkdir build
  - cd build
  - qmake ..
  - make -j4

notifications:
  irc:
    channels:
      - "irc.choopa.net#firebird-emu"
    on_success: change
    on_failure: always
    skip_join: true
